### ISSUE TITLE
Python-Mini-Games/rockpaperscissors.py

### ISSUE THREAD

**Issue by Anubhav722** [rajatkusumwal/Python-Mini-Games#1]
![spock_spock](https://cloud.githubusercontent.com/assets/20791676/22331197/25f82bae-e3f0-11e6-9607-fcd11c78fc09.png)

Second condition must tie

for advanced game developing visit : pygame.org

**Comment by rajatkusumwal** [comment]
Thank you so much anubhav you saved the world from feeding a wrong value into the function. :) 👍

**Comment by Anubhav722** [comment]
Thanks for the sarcasm. :p 
Cool. Try using list comprehensions i.e. one liners. They are faster. It is a special feature in python. (just a suggestion)
